-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.4.2
    hooks:
    -   id: flake8
        args: [--max-line-length=131]
    -   id: trailing-whitespace

-   repo: local
    hooks:
    -   id: py-unittest
        name: py-unittest
        language: script
        entry: ./run_all_tests.sh
        files: \.py$